# Site
repository: Ehsan1997/ehsan1997.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Muhammad Ehsan ul Haq
title: ML Researcher
email: ehsanulhaq18@gmail.com
website: ehsan1997.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: EhsanBinEjaz
github_username:  Ehsan1997
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ehsansonofejaz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Medium Blogs
  icon: fas fa-blog
  url: https://medium.com/@ehsanulhaq18
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ehsan and I'm a Machine Learning Researcher. I have applied Deep Learning in areas including but not limited to High Energy Physics, Molecule Generation, Aerial Imaging and Medical Imaging.

  I am most skilled in: <mark>Deep Learning</mark> and <mark>Computer Vision</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Anomaly Detection With Normalizing Flows
        link: github.com/Ehsan1997/NormalizingFlows_HEP
        # link_text: Project Website
        additional_links:
          - title:  Ehsan1997/NormalizingFlows_HEP
            icon: fab fa-github
            url: https://github.com/ML4SCI/MLBender/tree/main/Anomaly_Detection_with_Normalizing_Flows_Muhammad_Ehsan_ul_Haq
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Using Deep Generative Modelling to detect Anomalies in data coming from Large Hadron Collider. 
        description: | # this will include new lines to allow paragraphs
          This project was created using <mark>Pytorch</mark>. It implements Masked AutoRegressive Flows model for modelling the data distribution of events from LHC. The project allows for sampling new data points from the distribution as well as inferring whether a data point belongs to the background or signal (anomaly) distribution. 
          
      - layout: top-middle
        title: Aerial Object Detection
        link: github.com/Ehsan1997/ObjectDetection-FRCNN-YOLO-Retina
        # link_text: Project Website
        additional_links:
          - title:  Ehsan1997/ObjectDetection-FRCNN-YOLO-Retina
            icon: fab fa-github
            url: https://github.com/Ehsan1997/ObjectDetection-FRCNN-YOLO-Retina
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Detecting Vehicles from satellite images.
        description: | # this will include new lines to allow paragraphs
          This project explores the performance of different object detection models (YOLO-based, RCNN-based and RetinaNet (FPN-Based)) on aerial vehicle detection. "SIMD" dataset was used for this purpose. It was built using <mark>Tensorflow</mark>.
      
      - layout: top-middle
        title: Semantic Segmentation in Medical Imaging
        link: github.com/Ehsan1997/ImageSegmentation-UNET-DeepLab-SegNet
        # link_text: Project Website
        additional_links:
          - title:  Ehsan1997/ImageSegmentation-UNET-DeepLab-SegNet
            icon: fab fa-github
            url: https://github.com/Ehsan1997/ImageSegmentation-UNET-DeepLab-SegNet
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Nuclear Segmentation in digital microscopic tissues via Deep Learning based Computer Vision techniques.
        description: | # this will include new lines to allow paragraphs
          Using SOTA models in semantic segmentation (DeepLab, SegNet and UNet) nuclear segmentation was carried out. MonuSeg dataset was used. Built using <mark>Tensorflow</mark>.

      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ML4SCI
        link: ml4sci.org
        # link_text: boringcompany.com
        sub_title: Machine Learning Researcher
        caption: 2021
        quote: >
          Applying Machine Learning in High Energy Physics.
        description: | # this will include new lines to allow paragraphs
            Machine Learning has showed potential in various field, thus it only makes sense to apply it for High Energy Physics. During my work here, I applied Machine Learning for various tasks on Large Hadron Collider Dataset.
      - layout: left
        title: Freelance Project
        # link: ml4sci.org
        # link_text: boringcompany.com
        sub_title: Machine Learning Researcher
        caption: 2020
        quote: >
          Applying Machine Learning for molecule generation.
        description: | # this will include new lines to allow paragraphs
            Generating Molecules using Deep Learning requires knowledge of Generative Modelling and Natural Language Processing. Here, I applied Variational AutoEncoders for generating sequences of atoms that composed a molecule. This also allowed for latent walk, where new molecules could be generated.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National University of Sciences and Technology
        caption: 2015 - 2019
        sub_title: BE Software Engineering
        quote: >
          Ranked # 1 in Pakistan. Worldwide it is ranked at 143 for Computer Science while overall its position is 358.
        description: | # this will include new lines to allow paragraphs
          Software Engineering degree is an intensive program where the student is exposed to various real-world problems. Collaboration with various industries is also carried out.
      
      - layout: left
        title: National University of Sciences and Technology
        caption: 2019 - 2021
        sub_title: MS Computer Science
        quote: >
          Ranked # 1 in Pakistan. Worldwide it is ranked at 143 for Computer Science while overall its position is 358.
        description: | # this will include new lines to allow paragraphs
          Most of my degree is related to Deep Learning and Computer Vision. My thesis was in Vision based TV Analytics where I used principles from Software Engineering to apply Metric Learning to Live Video Streams from YouTube.



#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
